FaultDetector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'aibased/', include('aibased.urls')),
    url(r'notifications/', include('notifications.urls')),
]

aibased/urls.py
from django.conf.urls import url
from . import views

app_name = 'aibased'

urlpatterns = [
    # /aibased/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /aibased/monitor
    url(r'^monitor$', views.Monitor.as_view(), name='monitor'),

    # /aibased/fault
    url(r'^fault$', views.Fault.as_view(), name='fault'),

    # /aibased/ann
    url(r'^ann$', views.NeuralNetwork.as_view(), name='ann'),

    # music/album/register
    url(r'^signup/$', views.UserRegistrationView.as_view(), name='user-signup'),

    # music/album/login
    url(r'^login/$', views.UserLoginView.as_view(), name='user-login'),

    # music/album/logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='user-logout'),

]

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = 'notifications'

urlpatterns = [
    # /aibased/
    # url(r'^$', views.index(), name='index'),
    # url(r'^$', views.index),
]

aibased/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class TrainingLog(models.Model):
    # trained_by = models.CharField(max_length=20)
    trained_by = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField()
    train_ratio = models.IntegerField()
    algorithm_name = models.CharField(max_length=20)
    hidden_layer_nodes = models.IntegerField()
    accuracy_tested = models.BooleanField(default=False)
    trained_inputs = models.IntegerField()
    tested_inputs = models.IntegerField()
    accuracy = models.IntegerField()


class PreFault(models.Model):
    date = models.DateTimeField()
    location = models.CharField(max_length=200)
    fault = models.CharField(max_length=100)
    i_a = models.FloatField()
    i_b = models.FloatField()
    i_c = models.FloatField()
    v_a = models.FloatField()
    v_b = models.FloatField()
    v_c = models.FloatField()

aibased/forms.py
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

aibased/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import View
from .forms import RegisterForm, LoginForm
from .models import TrainingLog
from .models import PreFault
# from channels.channel import Group
from notifications import utils
from notifications.models import Room
import json
# from . import neural
from ArtificialNeuralNetwork import NeuralNets as staticnn
from ArtificialNeuralNetwork.NeuralNets import NeuralNets
# from ArtificialNeuralNetwork.NeuralNetwork import NeuralNetObject
from datetime import datetime, timedelta
import pytz


neural_object = staticnn.css


class IndexView(View):
    template_name = 'aibased/index.html'

    def get(self, request):
        return render(request, 'aibased/index.html', context=None)

    def post(self, request):
        return render(request, 'aibased/index.html', context=None)


class Monitor(generic.ListView):
    template_name = 'aibased/monitor.html'
    user = None

    def get(self, request):
        self.user = request.user
        self.form_class = LoginForm
        if self.user.is_authenticated():
            object_list = PreFault.objects.all().order_by('-id')[:3]  # limit t8o 3
            room = Room.objects.get(title="Room1")
            return render(request, self.template_name, {'faults': object_list, 'room': room})
        else:
            return redirect('aibased:user-login')

    def get_queryset(self):
        return PreFault.objects.all()


# aibased/monitor/fault
@method_decorator(csrf_exempt, name='dispatch')
class Fault(View):
    def get(self, request):
        return HttpResponse("OK")

    def post(self, request):
        received_json_data = json.loads(request.body.decode('utf-8'))

        location = received_json_data.get('location')
        v1 = received_json_data.get('v1')
        v2 = received_json_data.get('v2')
        v3 = received_json_data.get('v3')
        i1 = received_json_data.get('i1')
        i2 = received_json_data.get('i2')
        i3 = received_json_data.get('i3')
        lst = [v1, v2, v3, i1, i2, i3]

        neural_object = NeuralNets.clf

        result = neural_object.predict([lst])
        faults = NeuralNets.process_fault(result)

        now = datetime.now() + timedelta(hours=5, minutes=30)
        zone = pytz.timezone('Asia/Colombo')
        date_stamp = zone.localize(now)
        time_str = date_stamp.strftime('%H:%M:%S %d-%m-%Y')

        message = "A Fault has been occurred in {0} which is identified as a {1} fault at {2}".format(location,
                                                                                                      faults[0],
                                                                                                      time_str)

        r_message = {'message': message, 'position': location, 'fault': faults[0]}
        user = request.user
        room = utils.get_room_or_error(1, user)
        room.send_message(r_message, user)

        # save data to the database
        fault = PreFault(date=date_stamp, location=location, fault=faults[0], i_a=i1, i_b=i2, i_c=i3, v_a=v1, v_b=v2, v_c=v3)
        fault.save()

        return HttpResponse("Message Received")


class NeuralNetwork(View):
    user = None
    model = TrainingLog
    template_name = 'aibased/ann.html'

    def get(self, request):
        self.user = request.user
        if self.user.is_authenticated():
            recent_log = TrainingLog.objects.order_by('-id')[0]

            return render(request, self.template_name, {'log': recent_log})
        else:
            return render(request, 'aibased/index.html', context=None)

    def post(self, request):
        user = request.user
        check_tests = False
        algorithm = request.POST.get('algorithm')
        ratio = request.POST.get('ratio')
        ratio = int(ratio)
        h_l_nodes = request.POST.get('nodes')
        h_l_nodes = int(h_l_nodes)
        test_accuracy = request.POST.get('accuracy')
        if test_accuracy == 'on':
            check_tests = True

        ann = NeuralNets(algorithm=algorithm, h_l_size=h_l_nodes, ratio=ratio / 100)

        tr, tst, pred, acc = ann.run(test_accuracy=check_tests)

        date_stamp = datetime.now() + timedelta(hours=5, minutes=30)
        traing_log = TrainingLog(trained_by=user, time=date_stamp, train_ratio=ratio,
                                 algorithm_name=algorithm, hidden_layer_nodes=h_l_nodes, accuracy_tested=check_tests,
                                 trained_inputs=tr, tested_inputs=tst, accuracy=acc)
        traing_log.save()

        neural_object = ann.get_ann_classifier()
        recent_log = TrainingLog.objects.order_by('-id')[0]

        context = {'log': recent_log, 'trained': tr, 'tested': tst, 'correct': pred, 'accuracy': acc}
        return render(request, self.template_name, context)


class UserRegistrationView(View):
    form_class = RegisterForm
    template_name = 'aibased/user_form.html'

    # Display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (Normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns user object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('aibased:index')

        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = LoginForm
    template_name = 'aibased/user_form.html'

    # Display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        username = form.data.get('username')
        password = form.data.get('password')

        # returns user object if credentials are correct
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)

            return redirect('aibased:index')

        return render(request, self.template_name, {'form': form})


class UserLogoutView(View):
    form_class = RegisterForm

    def get(self, request):
        logout(request)
        return redirect('aibased:index')

templates/aibased/ann.html
{% extends 'aibased/base.html' %}

{% block ann %}class="active"{% endblock %}
{% block body %}
    <div class="container">
        <div>
            <div style="background-color: whitesmoke; opacity: 0.8">
                <div class="col-sm-4">
                    <h3 class="whiteSmoak">Trained Results of Neural Network</h3><br>
                    <div>
                        <table class="table table-hover table-striped" id="curved" style="background-color: #b4b4b4">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody id="resultTable">
                            <tr>
                                <td>Trained by:</td>
                                <td>{{ log.trained_by }}</td>
                            </tr>
                            <tr>
                                <td>Date Neural Network trained</td>
                                <td>{{ log.time }}</td>
                            </tr>
                            <tr>
                                <td>Ratio of trained data</td>
                                <td>{{ log.train_ratio }}</td>
                            </tr>
                            <tr>
                                <td>Algorithm used</td>
                                <td>{{ log.algorithm_name }}</td>
                            </tr>
                            <tr>
                                <td>No of hidden layer nodes</td>
                                <td>{{ log.hidden_layer_nodes }}</td>
                            </tr>
                            <tr>
                                <td>Accuracy</td>
                                <td>{{ log.accuracy }}</td>
                            </tr>
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div>
                    <h3 style="text-align: center; color: whitesmoke;">Neural Network Training</h3><br><br>
                </div>
                <div>
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label for="exampleInputEmail1" class="whiteSmoak">Train To Test Ratio (%)</label>
                                <input name="ratio" type="number" class="form-control" min="10" max="100"
                                       placeholder="0.0%">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8" id="algorithmType">
                                <label for="algorithmType" class="whiteSmoak">Algorithm Name</label>
                                <select class="form-control" name="algorithm" id="algorithm">
                                    <option>lbfgs</option>
                                    <option>adam</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label for="exampleInputEmail1" class="whiteSmoak">Hidden Layer Nodes</label>
                                <input name="nodes" type="number" class="form-control" min="2" max="10" placeholder="7">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <div class="checkbox">
                                    <label class="whiteSmoak">
                                        <input name="accuracy" type="checkbox"> Test Accuracy
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-offset-2 col-sm-8">
                            <button type="submit" class="btn btn-info">Train</button>
                        </div>
                    </form>
                </div>
            </div>

            <div style="background-color: whitesmoke; opacity: 0.8">
                <div class="col-sm-4">
                    <h3 class="whiteSmoak">Training Results of Neural Network</h3><br>
                    <div>
                        <table class="table table-hover table table-striped" id="curved"
                               style="background-color: #b4b4b4">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody id="resultTable">
                            <tr>
                                <td>No of Trained inputs</td>
                                <td>{{ trained }}</td>
                            </tr>
                            <tr>
                                <td>No of Tested inputs</td>
                                <td>{{ tested }}</td>
                            </tr>
                            <tr>
                                <td>No of correct Results</td>
                                <td>{{ correct }}</td>
                            </tr>
                            <tr>
                                <td>Accuracy(%)</td>
                                <td>{{ accuracy }}</td>
                            </tr>
                            </tbody>

                        </table>
                    </div>
                    {% if text %}
                        <h5 class="whiteSmoak">{{ text }}</h5>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/aibased/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    {#*******************************************************************************************************#}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine" type="text/css">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/Flash.png' %}"/>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>


    {#*******************************************************************************************************#}


    <!-- static files -->
    <!-- Latest compiled and minified CSS -->
    {#    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}"/>
    <script src="{% static "channels/js/websocketbridge.js" %}" type="text/javascript"></script>

    <!-- js -->
    {#    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>#}

    <!-- Latest compiled and minified JavaScript -->
    {#    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>#}
    {#*******************************************************************************************************#}


    <title>{% block title %}Fault Detector{% endblock %}</title>

</head>
<body>
<nav class="navbar navbar-inverse" style="border-color: dodgerblue">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'aibased:index' %}">
                <span class="glyphicon glyphicon-flash" aria-hidden="true">Fault Detector</span></a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            {% csrf_token %}
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li {% block monitor %}{% endblock %}>
                        <a href="{% url 'aibased:monitor' %}">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true">&nbsp;Monitor</span>
                        </a>
                    </li>
                    <li {% block ann %}{% endblock %}>
                        <a class="navbar-link" href="{% url 'aibased:ann' %}">
                            <span class="glyphicon glyphicon-education" aria-hidden="true">&nbsp;Neural Network</span>
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'aibased:user-logout' %}">
                            <span class="glyphicon glyphicon-off"
                                  aria-hidden="true">&nbsp;Logout {{ request.user }}</span>
                        </a>
                    </li>
                </ul>

            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'aibased:user-login' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true">&nbsp;Login</span>
                        </a>
                    </li>
                </ul>
            {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

<footer class="page-footer navbar-fixed-bottom">
    <div class="footer-copyright">
        <div class="container" style="color: #E46A68;">
            <marquee>© 2017 Power System Fault Detection with Artificial Neural Network</marquee>
        </div>
    </div>
</footer>
</body>
</html>

templates/aibased/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-3 text-danger">{{ field.label_tag }}</label>
        <div class="col-sm-9">
            <input type='{{ field.field.widget.input_type }}' class="form-control" id='{{ field.auto_id }}'
                   name='{{ field.name }}'>
        </div>
    </div>
{% endfor %}

templates/aibased/index.html
{% extends 'aibased/base.html' %}

{% block body %}
    <style>
        #frame {
            border-radius: 10px;
            border: 3px solid #E46A68;
            padding-top: 10px;
            height: 200px;
            background-color: whitesmoke;
            text-decoration-color: black;
            opacity: 0.8;
        }

        #ptext {
            text-align: justify;
        }

        h3 {
            color: dodgerblue;
            align-content: center;
        }
    </style>
    <div class="container">
        <!-- Project Title Animation begin -->
        <div class="text-center">
            <div style="text-align: center" id="typed-strings">
                <p><i>POWER SYSTEM</i></p>
                <p>FAULT <i>DETECTOR</i></p>
                <p>USING</p>
                <P>ARTIFICIAL <i>INTELLIGENCE</i></p>
                <p>POWER <i>FAULT</i> DETECTOR<br>USING <i>ARTIFICIAL</i> INTELLIGENCE</p>
            </div>
            <div style="background-attachment: fixed; height: 100px">
                <span id="typed" style="white-space:pre; text-align: center"></span>
            </div>
        </div>
        <!-- Project Title Animation end -->

        <div class="row" style="margin-top: 30px;">
            <div class="col-sm-4">
                <div class="col-sm-offset-1 col-sm-10" id="frame">
                    <h3>Fault Detection</h3>
                    <p id="ptext"><br>Faults can be identified by the system integrated in each location.
                        When there is an over current in distribution lines, the system reads the current values and
                        voltage
                        values and send to the server.</p>
                    <a class="btn btn-primary" href="/aibased/monitor" role="button">Goto <span
                            class="glyphicon glyphicon-arrow-right" aria-hidden="true">&nbsp</span></a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="col-sm-offset-1 col-sm-10" id="frame" style="height: 200px">
                    <h3>Train Neural Network</h3>
                    <p id="ptext"><br>The Neural Network can be trained by customizing number of nodes and the
                        algorithm. The accuracy
                        and test results will be displayed so if the training is not satisfied, it can be trained again.
                    </p>
                    <a class="btn btn-primary" href="/aibased/monitor" role="button">Goto <span
                            class="glyphicon glyphicon-arrow-right" aria-hidden="true">&nbsp</span></a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="col-sm-offset-1 col-sm-10" id="frame">
                    <h3>Online Monitoring</h3>
                    <p id="ptext"><br>Real time faults will be displayed on the monitoring system. Fault type, area,
                        date and time
                        can
                        be read as a notification. Previous faults also can be viewed through this monitoring
                        system.</p>
                    <a class="btn btn-primary" href="/aibased/monitor" role="button">Goto <span
                            class="glyphicon glyphicon-arrow-right" aria-hidden="true">&nbsp</span></a>
                </div>
            </div>
        </div>
    </div>
    {% load staticfiles %}
    <script src="{% static 'js/typed.js' %}" type="text/javascript"></script>
    <!-- banner-type-text -->
    <script>
        $(function () {
            $("#typed").typed({
                // strings: ["Typed.js is a <strong>jQuery</strong> plugin.", "It <em>types</em> out sentences.", "And then deletes them.", "Try it out!"],
                stringsElement: $('#typed-strings'),
                typeSpeed: 100,
                backDelay: 500,
                // true for continuous loop
                loop: true,
                contentType: 'html', // or text
                // defaults to false for infinite loop
                loopCount: false,
                callback: function () {
                    foo();
                },
                resetCallback: function () {
                    newTyped();
                }
            });

            $(".reset").click(function () {
                $("#typed").typed('reset');
            });

        });

        function newTyped() { /* A new typed object */
        }

        function foo() {
            console.log("Callback");
        }
    </script>
    <!-- //banner-type-text -->
{% endblock %}

templates/aibased/user_form.html
{% extends 'aibased/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}
    <div class="container">

            <div class="row" style="position:absolute; top: 50%; left: 50%; margin-right: -50%; transform: translate(-50%, -50%)">
{#                <div class="col-sm-offset-3 col-sm-6">#}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'aibased/form-template.html' %}
                        <div class="col-sm-offset-3">
                            <button class="btn btn-info" type="submit">Login</button>
                        </div>
                    </form>
{#                </div>#}
            </div>
    </div>
{% endblock %}